stages: 
  - build
  - test
  - deploy

variables:
  BUILD_DEBUG_DIR: build_debug
  CURRENT_IMAGE: ubuntu:24.04
  GIT_STRATEGY: clone
  GIT_DEPTH: 0

before_script:
  - apt-get update 
  - apt-get install -y git cmake build-essential libsqlite3-dev libncurses-dev lcov
  - git submodule sync --recursive
  - git submodule update --init --recursive

build-job-debug: 
  image: ${CURRENT_IMAGE}
  tags: 
    - docker
  stage: build
  script:
    - cmake -S . -B ${BUILD_DEBUG_DIR} -DCMAKE_BUILD_TYPE=Debug
    - cmake --build ${BUILD_DEBUG_DIR} --parallel 4
  artifacts:
    name: ${CI_PROJECT_NAME}_${CI_COMMIT_SHORT_SHA}_build
    paths:
      - ${BUILD_DEBUG_DIR}/Makefile
      - ${BUILD_DEBUG_DIR}/CPackSourceConfig.cmake
      - ${BUILD_DEBUG_DIR}/CPackConfig.cmake
      - ${BUILD_DEBUG_DIR}/tests/tests
      - ${BUILD_DEBUG_DIR}/**/*.a
      - ${BUILD_DEBUG_DIR}/src/server/server
      - ${BUILD_DEBUG_DIR}/src/client/client
      - ${BUILD_DEBUG_DIR}/**/*.gcno
    expire_in: 1 days

test-job:
  image: ${CURRENT_IMAGE}
  tags: 
    - docker
  stage: test
  script:
    - ./${BUILD_DEBUG_DIR}/tests/tests --gtest_output=xml:${BUILD_DEBUG_DIR}/tests/report.xml
  artifacts:
    name: ${CI_PROJECT_NAME}_${CI_COMMIT_SHORT_SHA}_test
    paths:
      - ${BUILD_DEBUG_DIR}/**/*.gcda
      - ${BUILD_DEBUG_DIR}/**/*.gcno
      - ${BUILD_DEBUG_DIR}/tests/report.xml
    reports:
      junit: ${BUILD_DEBUG_DIR}/tests/report.xml
    expire_in: 1 day
  needs: 
    - build-job-debug

coverage-job:
  image: ${CURRENT_IMAGE}
  tags:
    - docker
  stage: test
  script:
    - mkdir coverage/
    - lcov  --capture \
            --directory ${BUILD_DEBUG_DIR} \
            --output-file coverage/coverage.info \
            --no-external 
    - genhtml coverage/coverage.info --output-directory coverage/coverage-html
  artifacts:  
    name: ${CI_PROJECT_NAME}_${CI_COMMIT_SHORT_SHA}_coverage
    paths:  
      - coverage/coverage-html
      - coverage/coverage.info
    expire_in: 1 day
  needs:
    - test-job